name: Multiplatform build
on:
  push:
  schedule:
    - cron: '0 4 * * SUN'

jobs:
  compileAndTest:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - id: compile
        uses: pistocchifilippo/build_test_java@master
        with:
          phrase: CIAO
