name: Multiplatform build
on:
  - push
  schedule:
    - cron: '0 0 1 * *'
  #on version
  #cron

#env:
 # os: [ubuntu-latest, macos-latest, windows-latest]

jobs:
  compileAndTest:
    runs-on: ubuntu-latest #need
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew compileTestScala