name: Multiplatform build
on:
  push:
  schedule:
    - cron: '0 4 * * SUN'
  #on version
  #cron

#env:
 # os: [ubuntu-latest, macos-latest, windows-latest]

jobs:
  compileAndTest:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }} #need
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew compileTestScala