name: CI-build
on: push

systems: [ubuntu-latest,windows-latest]

jobs:
  compileAndTest:
    runs-on: ${{systems}}
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew compileTestScala