name: Multiplatform build
on:
  push:
  schedule:
    - cron: '0 4 * * SUN'

jobs:
  preliminary:
    name: preliminary build con ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - shell: bash
        run: ./gradlew compileScala
      - name: upload artifacts
      - shell: bash
        run: touch ok
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu_build
          path: ok
  test:
    needs: preliminary
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download artifacts #if: ${{ matrix.os }} == 'ubuntu'
        uses: actions/download-artifact@v2
        with:
          name: ubuntu_build
      - name: test
        run: ./gradlew test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo Deploy starts