name: CI-build
on: push
  #on version
  #cron

env:
  OS: [ubuntu-latest, macos-latest, windows-latest]

jobs:
  compileAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew compileTestScala