name: Multiplatform build
on:
  push:
  schedule:
    - cron: '0 4 * * SUN'

jobs:
  compileAndTest:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew compileTestScala
  deploy:
    runs-on: ubuntu-latest
    needs: compileAndTest
    steps:
      - run: echo Deploy starts